name: Test Discord Notification

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord message
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content":"✅ GitHub Actionsからのテスト通知です"}' \
          ${{ secrets.DISCORD_WEBHOOK }}
